class Login():
    Input_Email_XPATH = '//android.widget.EditText'
    Input_Password_XPATH = '//android.widget.EditText[@text="Password"]'
    Button_Security_XPATH = '//android.widget.Button[@content-desc="Security Policy"]'

    Button_Login_XPATH = '//android.widget.Button[@content-desc="LOGIN"]'
    Button_Cancel_XPATH = '//android.widget.TextView[@text="CANCEL"]'
    Verify_InvalidLogin_XPATH = '//android.widget.TextView[@text="Please provide valid details and try again"]'
    Button_Forgot_XPATH = '//android.widget.TextView[@text="Forgot Password?"]'
    Verify_ForgotPage_XPATH = '//*[contains(@content-desc,"ENTER YOUR EMAIL")]'
    Button_SignUp_XPATH = '//android.widget.TextView[@text="Sign up"]'
    Input_SigUpEmail_XPATH = '//android.widget.EditText[@text="Input email here"]'
    Verify_TC_XPATH = '//android.widget.TextView[@text="I agree to all the terms and conditions"]'
    Verify_Register_XPATH = '//*[contains(@content-desc,"REGISTER YOUR ACCOUNT")]'
    Button_Accept_XPATH = '//android.widget.TextView[@text="ACCEPT"]'
    Button_Register_XPATH = '//android.widget.Button[@content-desc="REGISTER"]'
    Verify_InvalidEmailError_XPATH = '//*[@text="Please provide valid details and try again"]'
    Verify_ContactUs_XPATH = '//*[@text="contact us on customercare@aldar.com"]'
    Button_ArabicLang_XPATH = '//android.widget.TextView[@text="عربي"]'
    Verify_ArabicLoginTitle_XPATH = '//android.widget.TextView[@text="تسجيل الدخول إلى حسابك"]'
    Button_EnglishLang_XPATH = '//android.widget.TextView[@text="EN"]'
    Verify_LoginTitle_XPATH = '//android.widget.TextView[@text="LOGIN TO YOUR ACCOUNT"]'

# class Home:
#     Verify_Welcome_XPATH = '//android.widget.TextView[@text="Welcome Back,"]'
#     Button_Notofication_XPATH = '//android.widget.ImageView[@content-desc="Notification bell icon"]'
#     Verify_Notif_NewCase_XPATH = '(//*[contains(@text,"New Case raised")])[1]'
#     Button_Call_XPATH= '//android.view.ViewGroup[@content-desc="󱆂"]'
#     Input_Subject_XPATH = '//android.widget.EditText[@text="Subject"]'
#     Input_Comment_XPATH = '//android.widget.EditText[@text="Comment"]'
#     Button_Submit_XPATH = '//android.widget.Button[@content-desc="SUBMIT"]'
#     Button_ViewJourney_XPATH = '//android.widget.TextView[@text="VIEW JOURNEY"]'
#     Verify_PropertyJourney_XPATH = '//android.widget.TextView[@text="PROPERTY JOURNEY"]'
#     Button_LearnMore_XPATH = '//android.view.ViewGroup[@content-desc="LEARN MORE"]'
#     Verify_ExploreMarketTrends_XPATH ='//*[contains(@text,"EXPLORE")]'
#     Button_ViewProperty_XPATH = '//android.widget.TextView[@text="VIEW PROPERTY DETAILS"]'
#     Verify_ViewProperty_XPATH = '//android.widget.TextView[@text="View Property Details"]'
#     Verify_StatementOfAccount_XPATH='//android.widget.TextView[@text="STATEMENT OF ACCOUNT"]'
#     Verify_ServiceRequest_XPATH = '(//android.widget.TextView[@text="Service Requests"])[1]'
#     Button_ViewAll_XPATH = '//android.widget.TextView[@text="View All"]'
#     Button_ViewDetails_XPATH = '//android.widget.TextView[@text="VIEW DETAILS"]'
#     Button_SearchBox_XPATH = '//android.widget.EditText'
#     Verify_Search_XPATH = '//android.widget.TextView[@text="SEARCH"]'
