name: Example Artifact Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Create a sample file to upload
      - name: Create sample file
        run: |
          echo "This is a sample file." > sample.txt
          echo "Sample file created."

      # Step 3: Upload the sample file as an artifact
      - name: Upload sample artifact
        uses: actions/upload-artifact@v3
        with:
          name: sample-file
          path: sample.txt  # This uploads sample.txt as an artifact

  download:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the 'build' job

    steps:
      # Step 4: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 5: Download the uploaded artifact
      - name: Download Sample Artifact
        uses: actions/download-artifact@v3
        with:
          name: sample-file
          path: ${{ github.workspace }}  # Download to the workspace

      # Step 6: List the files in the workspace
      - name: List downloaded files
        run: ls -al ${{ github.workspace }}  # List all files, including downloaded artifacts

      # Step 7: Display the contents of the downloaded file
      - name: Display contents of the sample file
        run: cat ${{ github.workspace }}/sample.txt  # Display the contents of sample.txt
